---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-app-dep
  labels:
    app: producer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      containers:
        - name: producer-app
          image: arturix/producersb:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: producer-app-svc
spec:
  selector:
    app: producer-app
  ports:
    - port: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: producer-app-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: producer-app-svc
              servicePort: 80
