kind: Service
apiVersion: v1
metadata:
  name: logstash-service
spec:
  selector:
    app: logstash
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
      nodePort: 323235