= Producer
v1.0, 2020-11-14
:toc:
:example-caption!:
:sectnums:
:sectnumlevels: 8
:icons: font
:source-highlighter: prettify

== Test java11 in docker image
[source]
----
cat >>Hello.java<<EOF
class Hello
{
    public static void main (String args[])
    {
        System.out.println("java 11 ok");
    }
}
EOF
----
[source]
----
cat >>Dockerfile<<EOF
FROM openjdk:11
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN javac Hello.java
CMD ["java", "Hello"]
EOF
----
[source]
docker build -t img-java-example .

[source]
docker run -it --rm img-java-example

== Install image locally

[source]
docker build -t producersb:1.0 .
docker images
docker run -p 8080:8080 producersb:1.0

http://192.168.56.10:8080/greeting

== Remove image from local docker
[source]
docker image rm --force 7a6f09a29ede

== Install docker image from link:https://hub.docker.com/repository/docker/arturix/producersb[docker hub]
[source]
docker run -p 8080:8080 arturix/producersb:latest

http://192.168.56.10:8080/

== Kafka
=== Install
==== On Docker
https://kafka-tutorials.confluent.io/kafka-console-consumer-producer-basics/kafka.html

[source]
docker-compose up -d

NOTE: *docker-compose.yml* is located at config-files/kafka-docker/docker-compose.yml

NOTE: Machine address 192.168.56.13

===== Test docker installation on windows
====== Producer
[source]
D:\kafka_2.13-2.6.0\bin\windows\kafka-console-producer --topic example-topic --bootstrap-server 192.168.56.13:29092

====== Consumer
[source]
D:\kafka_2.13-2.6.0\bin\windows\kafka-console-consumer --topic example-topic --bootstrap-server 192.168.56.13:29092

==== Helm
https://github.com/bitnami/charts/blob/master/bitnami/kafka/README.md#accessing-kafka-brokers-from-outside-the-cluster
[source]
helm repo add bitnami https://charts.bitnami.com/bitnami

[source]
helm install my-release bitnami/kafka

[source]
helm install my-release -f values.yaml bitnami/kafka

NOTE: values.yaml located at config-files/helm-kafka/values.yaml

===== Test helm installation on windows
====== Producer
[source]
D:\kafka_2.13-2.6.0\bin\windows\kafka-console-producer --topic example-topic --bootstrap-server 192.168.56.10:9094

====== Consumer
[source]
D:\kafka_2.13-2.6.0\bin\windows\kafka-console-consumer --topic example-topic --bootstrap-server 192.168.56.10:9094



== Bitbucket Pipeline
https://bitbucket.org/arturix/producersb/addon/pipelines/home#!/

== Run on K8s
[source]
kubectl apply -f producer.yaml

== Set namespace for prometheus monitoring on K8s
.monitoring-namespace.yaml
----
include::monitoring-namespace.yaml[]
----
== Install Prometheus
.prometheus.yaml
----
include::config-files/prometheus.yml[]
----

== ELK
=== ELK on local machine
[source]
D:\elastic\elasticsearch\bin\elasticsearch.bat

[source]
D:\elastic\kibana\bin\kibana.bat

[source]
D:\elastic\logstash\bin\logstash.bat -f D:\elastic\logstash\config\logstash.conf

http://localhost:5601/

Kibana->Stack Management->Index Patterns->Create index pattern

=== ELK using helm

[source]
helm repo add elastic https://helm.elastic.co

[source]
helm repo update

[source]
helm install elastic-operator elastic/eck-operator -n elastic-system --create-namespace

[source]
kubectl logs -n elastic-system sts/elastic-operator

[source]
kubectl -n elastic-system get sa