= Producer
v1.0, 2020-11-14
:toc:
:example-caption!:
:sectnums:
:sectnumlevels: 7
:icons: font
:source-highlighter: prettify

== Test java11 in docker image
[source]
----
cat >>Hello.java<<EOF
class Hello
{
    public static void main (String args[])
    {
        System.out.println("java 11 ok");
    }
}
EOF
----
[source]
----
cat >>Dockerfile<<EOF
FROM openjdk:11
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN javac Hello.java
CMD ["java", "Hello"]
EOF
----
[source]
docker build -t img-java-example .

[source]
docker run -it --rm img-java-example

== Install image locally

[source]
docker build -t producersb:1.0 .
docker images
docker run -p 8080:8080 producersb:1.0

http://192.168.56.10:8080/greeting

== Remove image from local docker
[source]
docker image rm --force 7a6f09a29ede

== Install docker image from link:https://hub.docker.com/repository/docker/arturix/producersb[docker hub]
[source]
docker run -p 8080:8080 arturix/producersb:latest

http://192.168.56.10:8080/

== Kafka
=== Install
==== Docker
https://kafka-tutorials.confluent.io/kafka-console-consumer-producer-basics/kafka.html

NOTE: Machine address 192.168.56.13

.config-files/kafka/docker-compose.yml
include::config-files/kafka/docker-compose.yml[]
[source]
docker-compose up -d

==== Test on windows
===== Producer
[source]
D:\kafka_2.13-2.6.0\bin\windows\kafka-console-producer --topic example-topic --bootstrap-server 192.168.56.13:29092

===== Consumer
[source]
D:\kafka_2.13-2.6.0\bin\windows\kafka-console-consumer --topic example-topic --bootstrap-server 192.168.56.13:29092

== Bitbucket Pipeline
https://bitbucket.org/arturix/producersb/addon/pipelines/home#!/

== Run on K8s
[source]
kubectl apply -f producer.yaml

== Set namespace for prometheus monitoring on K8s
.monitoring-namespace.yaml
----
include::monitoring-namespace.yaml[]
----
== Install Prometheus
.prometheus.yaml
----
include::config-files/prometheus.yml[]
----

=== ELK on local machine
[source]
D:\elastic\elasticsearch\bin\elasticsearch.bat

[source]
D:\elastic\kibana\bin\kibana.bat

[source]
D:\elastic\logstash\bin\logstash.bat -f D:\elastic\logstash\config\logstash.conf

http://localhost:5601/

Kibana->Stack Management->Index Patterns->Create index pattern