= Producer
v1.0, 2020-11-14
:toc:
:example-caption!:
:sectnums:
:sectnumlevels: 7
:icons: font
:source-highlighter: prettify

== Test java11 in docker image
[source]
----
cat >>Hello.java<<EOF
class Hello
{
    public static void main (String args[])
    {
        System.out.println("java 11 ok");
    }
}
EOF
----
[source]
----
cat >>Dockerfile<<EOF
FROM openjdk:11
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN javac Hello.java
CMD ["java", "Hello"]
EOF
----
[source]
docker build -t img-java-example .

[source]
docker run -it --rm img-java-example

== Install image locally

[source]
docker build -t producersb:1.0 .
docker images
docker run -p 8080:8080 producersb:1.0

http://192.168.56.10:8080/greeting

== Remove image from local docker
[source]
docker image rm --force 7a6f09a29ede

== Install docker image from link:https://hub.docker.com/repository/docker/arturix/producersb[docker hub]
[source]
docker run -p 8080:8080 arturix/producersb:latest

http://192.168.56.10:8080/

== Bitbucket Pipeline
https://bitbucket.org/arturix/producersb/addon/pipelines/home#!/

== Run on K8s
[source]
kubectl apply -f producer.yaml

== Install Kafka

[source]
helm repo add bitnami https://charts.bitnami.com/bitnami
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

* link:https://docs.bitnami.com/tutorials/deploy-scalable-kafka-zookeeper-cluster-kubernetes/[Instructions]
[source]
helm install zookeeper bitnami/zookeeper --set replicaCount=3 --set auth.enabled=false --set allowAnonymousLogin=true


----
** Please be patient while the chart is being deployed **

ZooKeeper can be accessed via port 2181 on the following DNS name from within your cluster:

    zookeeper.default.svc.cluster.local

To connect to your ZooKeeper server run the following commands:

    export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=zookeeper,app.kubernetes.io/instance=zookeeper,app.kubernetes.io/component=zookeeper" -o jsonpath="{.items[0].metadata.name}")
    kubectl exec -it $POD_NAME -- zkCli.sh

To connect to your ZooKeeper server from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/zookeeper 2181:2181 &
    zkCli.sh 127.0.0.1:2181
---

[source]
export ZOOKEEPER-SERVICE-NAME=zookeeper.default.svc.cluster.local
helm install kafka bitnami/kafka --set zookeeper.enabled=false --set replicaCount=3 --set externalZookeeper.servers=zookeeper.default.svc.cluster.local

---
** Please be patient while the chart is being deployed **

Kafka can be accessed by consumers via port 9092 on the following DNS name from within your cluster:

    kafka.default.svc.cluster.local

Each Kafka broker can be accessed by producers via port 9092 on the following DNS name(s) from within your cluster:

    kafka-0.kafka-headless.default.svc.cluster.local:9092
    kafka-1.kafka-headless.default.svc.cluster.local:9092
    kafka-2.kafka-headless.default.svc.cluster.local:9092

To create a pod that you can use as a Kafka client run the following commands:

    kubectl run kafka-client --restart='Never' --image docker.io/bitnami/kafka:2.6.0-debian-10-r78 --namespace default --command -- sleep infinity
    kubectl exec --tty -i kafka-client --namespace default -- bash

    PRODUCER:
        kafka-console-producer.sh \

            --broker-list kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092,kafka-2.kafka-headless.default.svc.cluster.local:9092 \
            --topic test

    CONSUMER:
        kafka-console-consumer.sh \

            --bootstrap-server kafka.default.svc.cluster.local:9092 \
            --topic test \
            --from-beginning
[1]+  Done                    kubectl port-forward --namespace default svc/zookeeper 2181:2181
---

[source]
export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
