---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-app-dep
  labels:
    app: es-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-app
  template:
    metadata:
      labels:
        app: es-app
    spec:
      containers:
        - name: es-app
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
          ports:
            - name: http
              containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: es-app-svc-ext
spec:
  selector:
    app: es-app
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: {{ .Values.ports.elasticsearch }}
      protocol: TCP