---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-auto
  labels:
    app: es-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-auto
  template:
    metadata:
      labels:
        app: es-auto
    spec:
      containers:
        - name: es-auto
          image: elasticsearch:7.8.0
          ports:
            - name: http
              containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: es-auto
spec:
  selector:
    app: es-auto
  type: LoadBalancer
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: {{ .Values.ports.elasticsearch }}
      protocol: TCP