---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kib-app-dep
  labels:
    app: kib-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kib-app
  template:
    metadata:
      labels:
        app: kib-app
    spec:
      containers:
        - name: kib-app
          image: docker.elastic.co/kibana/kibana:7.10.0
          ports:
            - name: http
              containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://{{ .Values.global.hostIp }}:{{ .Values.ports.elasticsearch }}
---
apiVersion: v1
kind: Service
metadata:
  name: kib-app-svc-ext
spec:
  selector:
    app: kib-app
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort:  {{ .Values.ports.kibana }}
      protocol: TCP