---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kib-auto-dep
  labels:
    app: kib-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kib-auto
  template:
    metadata:
      labels:
        app: kib-auto
    spec:
      containers:
        - name: kib-auto
          image: kibana:7.8.0
          ports:
            - name: http
              containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://{{ .Values.global.hostIp }}:{{ .Values.ports.elasticsearch }}
---
apiVersion: v1
kind: Service
metadata:
  name: kib-auto-ext-svc
spec:
  selector:
    app: kib-auto
  type: LoadBalancer
  ports:
    - port: 5601
      targetPort: 5601
      nodePort:  {{ .Values.ports.kibana }}
      protocol: TCP