---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-auto-pipeline
data:
  logstash.conf: |
  {{ .Files.Get "logstash.conf" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-auto-dep
  labels:
    app: log-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-auto
  template:
    metadata:
      labels:
        app: log-auto
    spec:
      containers:
        - name: log-auto
          image: logstash:7.8.0
          ports:
            - containerPort: 5044
              name: filebeat
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://{{ .Values.global.hostIp }}:{{ .Values.ports.elasticsearch }}
---
apiVersion: v1
kind: Service
metadata:
  name: log-auto-svc-ext
spec:
  selector:
    app: log-auto
  type: NodePort
  ports:
    - port: 5044
      nodePort: {{ .Values.ports.logstash }}
      protocol: TCP
      targetPort: 5044