---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-auto
  labels:
    app: log-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-auto
  template:
    metadata:
      labels:
        app: log-auto
    spec:
      containers:
        - name: log-auto
          image: docker.elastic.co/logstash/logstash:7.10.0
          ports:
            - name: filebeat
              containerPort: 5044
          env:
            - name: ELASTICSEARCH_HOSTS
              value: bababa
          volumeMounts:
            - name: log-auto-pipeline
              mountPath: /usr/share/logstash/pipeline/
          command:
            - logstash
      volumes:
        - name: log-auto-pipeline
          configMap:
            name: log-auto-pipeline
            items:
            - key: logstash.conf
              path: logstash.conf
---
apiVersion: v1
kind: Service
metadata:
  name: log-auto-svc-ext
spec:
  selector:
    app: log-auto
  type: NodePort
  ports:
    - port: 5044
      protocol: TCP
      targetPort: 5044