---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app
  labels:
    app: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
        - name: log-app
          image: docker.elastic.co/logstash/logstash:7.10.0
          ports:
            - name: filebeat
              containerPort: 5044
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://{{ .Values.global.hostIp }}:{{ .Values.ports.elasticsearch }}
          volumeMounts:
            - name: log-app-pipeline
              mountPath: /usr/share/logstash/pipeline/
          command:
            - logstash
      volumes:
        - name: log-app-pipeline
          configMap:
            name: log-app-pipeline
            items:
            - key: logstash.conf
              path: logstash.conf
---
apiVersion: v1
kind: Service
metadata:
  name: log-app-svc-ext
spec:
  selector:
    app: log-app
  type: NodePort
  ports:
    - port: 5044
      protocol: TCP
      targetPort: 5044
      nodePort: {{ .Values.ports.logstash }}