---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-app-dep
  labels:
    app: producer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      containers:
        - name: producer-app
          image: arturix/producersb:latest
          ports:
            - containerPort: 80
          env:
            - name: JAVA_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
---
apiVersion: v1
kind: Service
metadata:
  name: producer-app-ext-svc
spec:
  selector:
    app: producer-app
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.ports.producer }}
      protocol: TCP
